In [145]:
import numpy as np
import jax
import jax.numpy as jnp


eps = 0.01
jp = jnp.array([[1/4*(1-eps),3/4*(eps)],
                [1/4*(eps),3/4*(1-eps)]])


print(jp)
print(jp.sum())
X = jnp.sum(jp,axis=1)
Y = jnp.sum(jp,axis=0)


print(X)
print(Y)



[[0.2475 0.0075]
 [0.0025 0.7425]]
1.0
[0.255 0.745]
[0.25 0.75]


In [146]:
jp

Array([[0.2475, 0.0075],
       [0.0025, 0.7425]], dtype=float32)

In [154]:
print(X)
print(Y)
H_x = jnp.sum(-X * jnp.log2(X))
print(H_x)

[0.255 0.745]
[0.25 0.75]
0.8191072


In [155]:
H_x_y = -jnp.sum((jp * jnp.log2(jp/Y)))
print(H_x_y)


0.08079312


In [171]:
jp

Array([[0.2475, 0.0075],
       [0.0025, 0.7425]], dtype=float32)

In [160]:
H_x_Y = 0
for i in range(2):
    for j in range(2):
        H_x_Y += -X[i] * jp[i][j] / Y[j] * jnp.log2(jp[i][j] / Y[j])
print(H_x_Y)

0.08079311


In [177]:
jp

Array([[0.2475, 0.0075],
       [0.0025, 0.7425]], dtype=float32)

In [178]:
X/Y

Array([1.02      , 0.99333334], dtype=float32)

In [176]:
X * jp / Y

Array([[0.25245, 0.00745],
       [0.00255, 0.73755]], dtype=float32)

In [179]:
H_x_Y = -jnp.sum(X * jp / Y * jnp.log2(jp / Y))
H_x_Y

Array(0.08079312, dtype=float32)

In [185]:
2**H_x_Y

Array(1.0575993, dtype=float32)

In [172]:
jnp.allclose(-jnp.sum(X * jp / Y * jnp.log2(jp / Y)), -jnp.sum((jp * jnp.log2(jp/Y))))

Array(True, dtype=bool)

In [149]:

I_x_y = 0
for i in range(2):
    for j in range(2):
        res = jp[i][j]*jnp.log2(jp[i][j]/(X[i]*Y[j]))
        I_x_y+=res
print(I_x_y)

0.738314


In [150]:
I_x_y = jnp.sum(jp * jnp.log2(jp / (X[:, None] * Y[None, :])))
print(I_x_y)

0.738314


In [151]:
jnp.allclose(I_x_y, H_x - H_x_y)

Array(True, dtype=bool)

In [152]:
print(I_x_y, H_x - H_x_y)

0.738314 0.73831403


Basic marginalisation
$$p(x) = \sum_{y} p(x,y)$$
$$p(y) = \sum_{x} p(x,y)$$

Entropy
$$H(X) = -\sum_{x} p(x)\log_2 p(x)$$

Conditional entropy
$$H(X|Y) = -\sum_{x,y} p(x,y)\log_2 p(x|y)$$
$$= -\sum_{x,y} p(x,y)\log_2\frac{p(x,y)}{p(y)}$$

Mutual information (three equivalent forms)
$$I(X;Y) = \sum_{x,y} p(x,y)\log_2\frac{p(x,y)}{p(x)p(y)}$$
$$= H(X) - H(X|Y)$$
$$= H(Y) - H(Y|X)$$







